- name: ping the server
  hosts: frontend
  become: true
  tasks:
    - name: ping the server
      ansible.builtin.ping:

    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: present