- name: ping the servers
  hosts: frontend
  tasks: # list of tasks
  - name: ping the server
    ansible.builtin.ping:

  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: present