- name: play level variabls
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS # equal to COURSE=Ansible in shell, in Shell we refer $VAR or ${VAR}
    DURATION: 5 days
    TRAINER: Siva
  tasks:
    - name: print info
      vars:
        COURSE: Ansible
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }} course for {{ DURATION }} by {{ TRAINER }}"