- name: variables from files
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: print info
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }} course for {{ DURATION }} by {{ TRAINER }}"
  