- name: variables from inventory
  hosts: local
  connection: local
  tasks:
    - name: print info
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }} course for {{ DURATION }} by {{ TRAINER }}"
  